micronaut:
  server:
    port: 8081

tracing:
  jaeger:
    enabled: true
    sender:
      agentHost: localhost
      agentPort: 6831
    sampler:
      probability: 1

datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL57Dialect
    url: jdbc:mysql://localhost:3306/locadora?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: mk2lm002

jpa:
  default:
    entity-scan:
      packages: 'com.treino.persistence'
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true

flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false

grpc:
  server:
    port: 50052